### PR TITLE
Flash messages

### PR DESCRIPTION
**Pull request by PKilgarriff**
Added conditional display of flash_messaage into header - added some body tags and merged new changes from main

### CODE REVIEW

**Comment by PKilgarriff** [comment]
Updated the controller to use the new flash_message functionality - should be available to anyone who wishes to use them by setting the session[:flash_message] in the controller route

Be aware that they expect to then be redirected, so will not display if you open a view directly - in this case it would be better to write the @flash_message instance variable directly

**Comment by PKilgarriff** [comment]
Hold up on this actually - I forgot to use the same wording as the feature tests for User sign-in and out so need to update them

**Comment by PKilgarriff** [comment]
Good to go - updated the messages to match what we were already expecting in the feature tests

**Review by arhussain1 — APPROVED** [review]
Looks great

**Pull request merged**
